const { Pool } = require("pg"); require("dotenv").config({ path: "../.env" }); const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const foods = [
  {name:"Jollof Rice Deluxe",price:28,category:"rice",description:"Premium smoked paprika jollof rice with grilled chicken, plantain, and signature spice blend.",image:"https://images.unsplash.com/photo-1604329760661-e71dc83f8b26?w=600",rating:4.9,addons:[{id:"a1",name:"Extra Chicken",price:6},{id:"a2",name:"Beef Suya",price:7}]},
  {name:"Egusi Soup & Pounded Yam",price:24,category:"soups",description:"Rich melon seed egusi soup with assorted meat, served with smooth pounded yam.",image:"https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600",rating:4.8,addons:[{id:"a1",name:"Extra Meat",price:6},{id:"a3",name:"Fish",price:5}]},
  {name:"Suya Platter",price:32,category:"grills",description:"Spiced grilled beef suya with yaji peanut rub, sliced onion, tomatoes, and fresh pepper sauce.",image:"https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600",rating:4.9,addons:[{id:"a1",name:"Extra Skewer",price:5},{id:"a2",name:"Kilishi",price:6}]},
  {name:"Ofada Rice & Ayamase",price:26,category:"rice",description:"Local ofada rice with spicy green ayamase sauce, assorted meat, and fried plantain.",image:"https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600",rating:4.7,addons:[{id:"a2",name:"Beef",price:5},{id:"a3",name:"Fish",price:6}]},
  {name:"Grilled Tilapia & Chips",price:30,category:"grills",description:"Whole grilled tilapia with herb butter, served with crispy golden fries and tangy coleslaw.",image:"https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=600",rating:4.8,addons:[{id:"a4",name:"Plantain",price:3.5},{id:"a5",name:"Garlic Sauce",price:2}]},
  {name:"Pepper Soup Platter",price:22,category:"soups",description:"Aromatic catfish pepper soup with traditional herbs, served hot with yam cubes.",image:"https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600",rating:4.6,addons:[{id:"a5",name:"Yam",price:3},{id:"a8",name:"Bread",price:2}]},
  {name:"Fried Rice Supreme",price:26,category:"rice",description:"Nigerian-style fried rice with mixed vegetables, liver, shrimp, and spiced chicken.",image:"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600",rating:4.7,addons:[{id:"a1",name:"Extra Chicken",price:6},{id:"a3",name:"Shrimp",price:8}]},
  {name:"Banga Stew & Starch",price:27,category:"soups",description:"Palm nut banga stew with fresh catfish, ope, and smooth starch swallow.",image:"https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600",rating:4.8,addons:[{id:"a3",name:"Extra Fish",price:8},{id:"a10",name:"Dried Fish",price:4}]},
];
async function seed(){const c=await pool.connect();try{await c.query("DELETE FROM foods");for(const f of foods)await c.query("INSERT INTO foods(name,price,category,description,image,rating,addons)VALUES($1,$2,$3,$4,$5,$6,$7)",[f.name,f.price,f.category,f.description,f.image,f.rating,JSON.stringify(f.addons)]);console.log(`Seeded ${foods.length} items`)}finally{c.release();await pool.end()}}seed().catch(console.error);
